// ============================================================
// Infinall Chat - 100+ Marketing Tools Directory Catalog
// Comprehensive ecosystem across Paid Media, Analytics, SEO,
// CRM & Lifecycle, CRO & Creative, and Automation.
// ============================================================

export type ToolCategory =
  | 'all'
  | 'paid_media'
  | 'analytics'
  | 'seo_scraping'
  | 'crm_retention'
  | 'cro_creative'
  | 'automation';

export interface ToolDirectoryItem {
  id: string;
  name: string;
  category: ToolCategory;
  description: string;
  icon: string;
  status: 'active' | 'mock' | 'requires_auth';
  latencyMs: number;
  tags: string[];
  mcpServer?: string;
  sampleQuery?: string;
  /** Connector envKey (META/GA4/GOOGLE_ADS/FIRECRAWL) => live status is derived dynamically. */
  envKey?: 'META' | 'GA4' | 'GOOGLE_ADS' | 'FIRECRAWL';
}

export const DIRECTORY_TOOLS: ToolDirectoryItem[] = [
  // ============================================================
  // 1. PAID MEDIA & ACQUISITION (10 Tools)
  // ============================================================
  {
    id: 'meta_ads_manager',
    name: 'Meta Ads Manager API',
    category: 'paid_media',
    description: 'Create, read, and mutate Facebook & Instagram ad campaigns, ad sets, and creative budgets.',
    icon: 'Megaphone',
    status: 'active',
    latencyMs: 145,
    tags: ['Facebook', 'Instagram', 'Advantage+', 'CPA'],
    mcpServer: 'meta-ads-mcp',
    sampleQuery: 'Get ROAS and spend breakdown for active campaigns',
    envKey: 'META',
  },
  {
    id: 'google_ads_api',
    name: 'Google Ads API',
    category: 'paid_media',
    description: 'Access Search, Performance Max, Display, and YouTube ad campaign telemetry and keywords.',
    icon: 'Target',
    status: 'active',
    latencyMs: 160,
    tags: ['Google Search', 'PMax', 'YouTube Ads', 'Keywords'],
    mcpServer: 'google-ads-mcp',
    sampleQuery: 'Fetch top converting search terms with CPC < $5.00',
    envKey: 'GOOGLE_ADS',
  },
  {
    id: 'tiktok_ads_business',
    name: 'TikTok Ads for Business',
    category: 'paid_media',
    description: 'Manage Spark Ads, Video Shopping Ads, and TikTok Creator Marketplace campaigns.',
    icon: 'Video',
    status: 'mock',
    latencyMs: 180,
    tags: ['TikTok', 'Spark Ads', 'Short-form Video', 'Gen Z'],
    mcpServer: 'tiktok-ads-mcp',
    sampleQuery: 'Analyze top creative hook drop-off curves',
  },
  {
    id: 'linkedin_campaign_manager',
    name: 'LinkedIn Campaign Manager',
    category: 'paid_media',
    description: 'Target B2B accounts, job titles, and company sizes with Sponsored Content and InMail.',
    icon: 'Briefcase',
    status: 'mock',
    latencyMs: 210,
    tags: ['B2B', 'Account Based Marketing', 'Job Titles', 'Lead Gen'],
    mcpServer: 'linkedin-mcp',
    sampleQuery: 'Pull C-Suite engagement by company size tier',
  },
  {
    id: 'amazon_ads_dsp',
    name: 'Amazon Advertising & DSP',
    category: 'paid_media',
    description: 'Sponsored Products, Sponsored Brands, and programmatic DSP retail media targeting.',
    icon: 'ShoppingBag',
    status: 'mock',
    latencyMs: 230,
    tags: ['E-commerce', 'Sponsored Products', 'Retail Media', 'ACOS'],
    mcpServer: 'amazon-ads-mcp',
  },
  {
    id: 'pinterest_ads_manager',
    name: 'Pinterest Ads API',
    category: 'paid_media',
    description: 'Promoted Pins, Shopping Catalog sync, and visual intent search targeting.',
    icon: 'Pin',
    status: 'mock',
    latencyMs: 195,
    tags: ['Visual Search', 'Shopping', 'Lifestyle', 'Inspiration'],
    mcpServer: 'pinterest-mcp',
  },
  {
    id: 'twitter_x_ads',
    name: 'X (Twitter) Ads API',
    category: 'paid_media',
    description: 'Trend Takeovers, Promoted Posts, and follower lookalike keyword targeting.',
    icon: 'Share2',
    status: 'mock',
    latencyMs: 175,
    tags: ['Real-time', 'Trending', 'Keyword Targeting'],
    mcpServer: 'x-ads-mcp',
  },
  {
    id: 'reddit_ads_business',
    name: 'Reddit Ads Community Targeting',
    category: 'paid_media',
    description: 'Subreddit context targeting, conversation placement, and niche enthusiast reach.',
    icon: 'MessageCircle',
    status: 'mock',
    latencyMs: 190,
    tags: ['Subreddits', 'Communities', 'Niche Audiences'],
    mcpServer: 'reddit-mcp',
  },
  {
    id: 'microsoft_bing_ads',
    name: 'Microsoft Advertising',
    category: 'paid_media',
    description: 'Bing Search, Copilot placements, and LinkedIn Profile audience bidding on Windows.',
    icon: 'Search',
    status: 'mock',
    latencyMs: 165,
    tags: ['Bing', 'Copilot', 'Desktop Enterprise', 'Low CPC'],
    mcpServer: 'msft-ads-mcp',
  },
  {
    id: 'youtube_video_ads',
    name: 'YouTube Video & Shorts Ads',
    category: 'paid_media',
    description: 'TrueView In-Stream, Non-skippable bumpers, and YouTube Shorts video action campaigns.',
    icon: 'Youtube',
    status: 'mock',
    latencyMs: 185,
    tags: ['Video Action', 'Shorts', 'Brand Lift', 'CPV'],
    mcpServer: 'youtube-ads-mcp',
  },

  // ============================================================
  // 2. ANALYTICS & ATTRIBUTION (10 Tools)
  // ============================================================
  {
    id: 'google_analytics_4',
    name: 'Google Analytics 4 (GA4)',
    category: 'analytics',
    description: 'Real-time event tracking, multi-channel attribution paths, conversion rates, and bounce metrics.',
    icon: 'BarChart2',
    status: 'active',
    latencyMs: 120,
    tags: ['GA4', 'Sessions', 'Attribution', 'Events', 'Conversion Rate'],
    mcpServer: 'ga4-mcp',
    sampleQuery: 'Pull organic search vs paid social assisted conversions',
    envKey: 'GA4',
  },
  {
    id: 'mixpanel_product_analytics',
    name: 'Mixpanel Product Analytics',
    category: 'analytics',
    description: 'Product event telemetry, cohort retention analysis, and user funnel drop-offs.',
    icon: 'Activity',
    status: 'mock',
    latencyMs: 135,
    tags: ['Funnels', 'Cohorts', 'Product Growth', 'Retention'],
    mcpServer: 'mixpanel-mcp',
  },
  {
    id: 'amplitude_analytics',
    name: 'Amplitude Behavioral Analytics',
    category: 'analytics',
    description: 'Behavioral cohorting, customer journey mapping, and milestone conversion metrics.',
    icon: 'Compass',
    status: 'mock',
    latencyMs: 140,
    tags: ['Journeys', 'Behavioral Cohorts', 'Milestones'],
    mcpServer: 'amplitude-mcp',
  },
  {
    id: 'segment_cdp',
    name: 'Twilio Segment CDP',
    category: 'analytics',
    description: 'Customer data platform identity resolution and real-time event pipeline routing.',
    icon: 'Share2',
    status: 'mock',
    latencyMs: 110,
    tags: ['CDP', 'Identity Resolution', 'Pipelines'],
    mcpServer: 'segment-mcp',
  },
  {
    id: 'posthog_os',
    name: 'PostHog Analytics Suite',
    category: 'analytics',
    description: 'Session replay, feature flags, A/B experimentation, and custom product telemetry.',
    icon: 'Cpu',
    status: 'mock',
    latencyMs: 125,
    tags: ['Session Replay', 'Feature Flags', 'A/B Tests'],
    mcpServer: 'posthog-mcp',
  },
  {
    id: 'heap_analytics',
    name: 'Heap Automated Analytics',
    category: 'analytics',
    description: 'Autocapture digital experience insights, retro-active event definition, and funnel auditing.',
    icon: 'Layers',
    status: 'mock',
    latencyMs: 130,
    tags: ['Autocapture', 'Retroactive', 'Funnels'],
    mcpServer: 'heap-mcp',
  },
  {
    id: 'fullstory_dxp',
    name: 'FullStory Digital Experience',
    category: 'analytics',
    description: 'Friction scoring, rage-click detection, dead-click analysis, and qualitative session replays.',
    icon: 'Eye',
    status: 'mock',
    latencyMs: 150,
    tags: ['Rage Clicks', 'Friction Points', 'Session Insights'],
    mcpServer: 'fullstory-mcp',
  },
  {
    id: 'triple_whale_attribution',
    name: 'Triple Whale E-commerce Attribution',
    category: 'analytics',
    description: 'First-party pixel attribution (Triple Pixel), blended ROAS, and cohort LTV forecasting.',
    icon: 'PieChart',
    status: 'mock',
    latencyMs: 145,
    tags: ['Shopify', 'Triple Pixel', 'Blended ROAS', 'LTV'],
    mcpServer: 'triple-whale-mcp',
  },
  {
    id: 'northbeam_mmm',
    name: 'Northbeam MMM & Multi-Touch',
    category: 'analytics',
    description: 'Marketing mix modeling (MMM), media efficiency ratio (MER), and post-iOS14 touchpoint tracking.',
    icon: 'TrendingUp',
    status: 'mock',
    latencyMs: 170,
    tags: ['MMM', 'MER', 'Cross-Channel Modeling'],
    mcpServer: 'northbeam-mcp',
  },
  {
    id: 'adjust_mobile_mmp',
    name: 'Adjust Mobile MMP',
    category: 'analytics',
    description: 'App install attribution, deep linking campaigns, SKAdNetwork modeling, and in-app revenue tracking.',
    icon: 'Smartphone',
    status: 'mock',
    latencyMs: 160,
    tags: ['MMP', 'SKAN 4.0', 'App Installs', 'Deep Linking'],
    mcpServer: 'adjust-mcp',
  },

  // ============================================================
  // 3. SEO & SCRAPING (10 Tools)
  // ============================================================
  {
    id: 'firecrawl_web_crawler',
    name: 'Firecrawl LLM Scraper',
    category: 'seo_scraping',
    description: 'Extract clean markdown, structured tables, and pricing from dynamic JavaScript websites.',
    icon: 'Flame',
    status: 'active',
    latencyMs: 250,
    tags: ['Web Scraping', 'Markdown Extraction', 'Competitor Research'],
    mcpServer: 'firecrawl-mcp',
    sampleQuery: 'Scrape competitor pricing page into clean markdown table',
    envKey: 'FIRECRAWL',
  },
  {
    id: 'web_search_tavily',
    name: 'Tavily Deep Web Search',
    category: 'seo_scraping',
    description: 'Factual, up-to-date web intelligence with instant citation extraction and content scoring.',
    icon: 'Globe',
    status: 'active',
    latencyMs: 220,
    tags: ['Live Web', 'Citations', 'Search Grounding'],
    mcpServer: 'tavily-mcp',
  },
  {
    id: 'google_search_console',
    name: 'Google Search Console API',
    category: 'seo_scraping',
    description: 'Query rankings, organic impressions, click-through rates, and index coverage errors.',
    icon: 'Search',
    status: 'mock',
    latencyMs: 175,
    tags: ['Rankings', 'Organic CTR', 'Impressions', 'Indexation'],
    mcpServer: 'gsc-mcp',
  },
  {
    id: 'semrush_domain_analytics',
    name: 'SEMrush Keyword & Domain Intelligence',
    category: 'seo_scraping',
    description: 'Organic competitor keyword gap analysis, backlink authority, and search volume databases.',
    icon: 'Layers',
    status: 'mock',
    latencyMs: 220,
    tags: ['Keyword Gap', 'Backlinks', 'Search Volume', 'Domain Authority'],
    mcpServer: 'semrush-mcp',
  },
  {
    id: 'ahrefs_site_explorer',
    name: 'Ahrefs SEO & Content Explorer',
    category: 'seo_scraping',
    description: 'Backlink profiles, referring domains, organic keyword distribution, and content gap teardowns.',
    icon: 'Globe',
    status: 'mock',
    latencyMs: 215,
    tags: ['Backlinks', 'Content Gap', 'Referring Domains'],
    mcpServer: 'ahrefs-mcp',
  },
  {
    id: 'moz_pro_metrics',
    name: 'Moz Pro Domain Authority API',
    category: 'seo_scraping',
    description: 'Domain Authority (DA), Page Authority (PA), and spam score auditing across SERPs.',
    icon: 'Award',
    status: 'mock',
    latencyMs: 190,
    tags: ['Domain Authority', 'Spam Score', 'SERP Overlays'],
    mcpServer: 'moz-mcp',
  },
  {
    id: 'screaming_frog_crawler',
    name: 'Screaming Frog SEO Spider Engine',
    category: 'seo_scraping',
    description: 'Technical SEO audits, broken link checking, canonical tag validation, and XML sitemap parsing.',
    icon: 'Code',
    status: 'mock',
    latencyMs: 260,
    tags: ['Technical SEO', 'Status Codes', 'Redirect Chains'],
    mcpServer: 'screaming-frog-mcp',
  },
  {
    id: 'surfer_seo_analyzer',
    name: 'Surfer SEO Content Intelligence',
    category: 'seo_scraping',
    description: 'NLP keyword density recommendations, heading structures, and SERP content score modeling.',
    icon: 'FileText',
    status: 'mock',
    latencyMs: 195,
    tags: ['NLP Keywords', 'Content Score', 'SERP Benchmarks'],
    mcpServer: 'surfer-mcp',
  },
  {
    id: 'clearscope_relevance',
    name: 'Clearscope Search Intent Scorer',
    category: 'seo_scraping',
    description: 'Search intent categorization, topic coverage grades, and readability benchmarks.',
    icon: 'CheckSquare',
    status: 'mock',
    latencyMs: 180,
    tags: ['Search Intent', 'Topic Coverage', 'Readability'],
    mcpServer: 'clearscope-mcp',
  },
  {
    id: 'spyfu_competitor_intel',
    name: 'SpyFu Competitor History',
    category: 'seo_scraping',
    description: '15-year Google Ad history, organic keyword ranking timeline, and competitor ad copy archive.',
    icon: 'History',
    status: 'mock',
    latencyMs: 205,
    tags: ['Ad History', 'Organic Ranking Timeline', 'Ad Copy Archive'],
    mcpServer: 'spyfu-mcp',
  },

  // ============================================================
  // 4. CRM & RETENTION LIFECYCLE (10 Tools)
  // ============================================================
  {
    id: 'hubspot_crm_api',
    name: 'HubSpot Marketing Hub',
    category: 'crm_retention',
    description: 'Contact lists, lead scoring workflows, email campaigns, and CRM deal pipeline telemetry.',
    icon: 'Users',
    status: 'active',
    latencyMs: 155,
    tags: ['HubSpot', 'Workflows', 'MQLs', 'Deal Pipelines', 'Forms'],
    mcpServer: 'hubspot-mcp',
    sampleQuery: 'Fetch all deals in negotiation stage with expected close this month',
  },
  {
    id: 'salesforce_marketing_cloud',
    name: 'Salesforce Marketing Cloud & CRM',
    category: 'crm_retention',
    description: 'Enterprise omnichannel customer journeys, lead routing, and opportunity attribution.',
    icon: 'Cloud',
    status: 'mock',
    latencyMs: 240,
    tags: ['Salesforce', 'Enterprise CRM', 'Lead Routing', 'Opportunity Attribution'],
    mcpServer: 'salesforce-mcp',
  },
  {
    id: 'klaviyo_ecommerce_crm',
    name: 'Klaviyo Email & SMS',
    category: 'crm_retention',
    description: 'E-commerce lifecycle flows, abandoned cart triggers, and predictive customer LTV.',
    icon: 'Mail',
    status: 'mock',
    latencyMs: 140,
    tags: ['E-commerce', 'Klaviyo', 'Abandoned Cart', 'SMS Marketing'],
    mcpServer: 'klaviyo-mcp',
  },
  {
    id: 'customerio_journeys',
    name: 'Customer.io Automated Journeys',
    category: 'crm_retention',
    description: 'Event-triggered messaging pipelines, in-app messages, push notifications, and webhooks.',
    icon: 'Send',
    status: 'mock',
    latencyMs: 130,
    tags: ['Event-Driven', 'In-App Messages', 'Push Notifications'],
    mcpServer: 'customerio-mcp',
  },
  {
    id: 'braze_customer_engagement',
    name: 'Braze Engagement Platform',
    category: 'crm_retention',
    description: 'Cross-channel canvas orchestration, Content Cards, and real-time behavioral segmentation.',
    icon: 'Sparkles',
    status: 'mock',
    latencyMs: 160,
    tags: ['Braze Canvas', 'Content Cards', 'Push Notifications'],
    mcpServer: 'braze-mcp',
  },
  {
    id: 'activecampaign_cx',
    name: 'ActiveCampaign CX Automation',
    category: 'crm_retention',
    description: 'Visual automation builder, dynamic email content tags, and site tracking triggers.',
    icon: 'GitBranch',
    status: 'mock',
    latencyMs: 145,
    tags: ['Visual Automation', 'Email Marketing', 'Lead Scoring'],
    mcpServer: 'activecampaign-mcp',
  },
  {
    id: 'mailchimp_marketing',
    name: 'Mailchimp Transactional & Campaigns',
    category: 'crm_retention',
    description: 'Email newsletter broadcasts, customer journeys, and automated transactional Mandrill emails.',
    icon: 'Mail',
    status: 'mock',
    latencyMs: 135,
    tags: ['Newsletters', 'Mandrill', 'Audience Tags'],
    mcpServer: 'mailchimp-mcp',
  },
  {
    id: 'intercom_support_messenger',
    name: 'Intercom Product Tours & Support',
    category: 'crm_retention',
    description: 'Proactive live chat banners, self-serve product tours, and customer conversation triage.',
    icon: 'MessageSquare',
    status: 'mock',
    latencyMs: 125,
    tags: ['Live Chat', 'Product Tours', 'Fin AI Agent'],
    mcpServer: 'intercom-mcp',
  },
  {
    id: 'pipedrive_sales_crm',
    name: 'Pipedrive Pipeline Management',
    category: 'crm_retention',
    description: 'Activity-based sales tracking, stage conversion rates, and revenue forecasting.',
    icon: 'DollarSign',
    status: 'mock',
    latencyMs: 130,
    tags: ['Sales Pipeline', 'Deal Stages', 'Forecasting'],
    mcpServer: 'pipedrive-mcp',
  },
  {
    id: 'attentive_sms_marketing',
    name: 'Attentive Conversational SMS',
    category: 'crm_retention',
    description: 'TCPA-compliant SMS subscriber capture, two-way text concierge, and flash sale broadcasts.',
    icon: 'Phone',
    status: 'mock',
    latencyMs: 140,
    tags: ['SMS', 'TCPA Compliant', 'Conversational Commerce'],
    mcpServer: 'attentive-mcp',
  },

  // ============================================================
  // 5. CRO, CMS & CREATIVE (6 Tools)
  // ============================================================
  {
    id: 'optimizely_experimentation',
    name: 'Optimizely Web Experimentation',
    category: 'cro_creative',
    description: 'Statistical significance A/B testing, multivariate test variant allocation, and feature flags.',
    icon: 'Percent',
    status: 'mock',
    latencyMs: 160,
    tags: ['A/B Testing', 'Multivariate', 'Stats Engine'],
    mcpServer: 'optimizely-mcp',
  },
  {
    id: 'vwo_conversion_suite',
    name: 'VWO Full CRO Engine',
    category: 'cro_creative',
    description: 'Heatmaps, scrollmaps, form abandon analytics, and low-code landing page personalization.',
    icon: 'Layers',
    status: 'mock',
    latencyMs: 150,
    tags: ['Heatmaps', 'Scrollmaps', 'Personalization'],
    mcpServer: 'vwo-mcp',
  },
  {
    id: 'shopify_storefront_admin',
    name: 'Shopify Storefront & Admin GraphQL',
    category: 'cro_creative',
    description: 'Product catalog sync, inventory levels, cart abandonment rates, and discount coupon creation.',
    icon: 'ShoppingBag',
    status: 'active',
    latencyMs: 135,
    tags: ['E-commerce', 'Discounts', 'Orders', 'Cart Recovery'],
    mcpServer: 'shopify-mcp',
  },
  {
    id: 'webflow_cms_api',
    name: 'Webflow Headless CMS',
    category: 'cro_creative',
    description: 'Publish landing pages, update programmatic SEO collections, and inject dynamic forms.',
    icon: 'Layout',
    status: 'mock',
    latencyMs: 145,
    tags: ['Landing Pages', 'Programmatic SEO', 'Design System'],
    mcpServer: 'webflow-mcp',
  },
  {
    id: 'canva_connect_api',
    name: 'Canva Design & Asset Automation',
    category: 'cro_creative',
    description: 'Auto-generate branded social creatives, ad banners, and slide templates with brand kit colors.',
    icon: 'Image',
    status: 'mock',
    latencyMs: 240,
    tags: ['Brand Kit', 'Social Banners', 'Creative Automation'],
    mcpServer: 'canva-mcp',
  },
  {
    id: 'unbounce_smart_builder',
    name: 'Unbounce Smart Traffic Builder',
    category: 'cro_creative',
    description: 'AI-powered landing page routing, dynamic text replacement, and conversion rate optimization.',
    icon: 'ExternalLink',
    status: 'mock',
    latencyMs: 170,
    tags: ['Landing Pages', 'Dynamic Text', 'Conversion Rate'],
    mcpServer: 'unbounce-mcp',
  },

  // ============================================================
  // 6. AUTOMATION & WORKSPACE OPS (6 Tools)
  // ============================================================
  {
    id: 'zapier_webhook_actions',
    name: 'Zapier App Integrations',
    category: 'automation',
    description: 'Connect with 6,000+ business applications via automated triggers and webhook actions.',
    icon: 'Zap',
    status: 'active',
    latencyMs: 190,
    tags: ['Webhooks', '6000+ Apps', 'Multi-step Zaps'],
    mcpServer: 'zapier-mcp',
  },
  {
    id: 'slack_growth_bot',
    name: 'Slack Marketing Notifications',
    category: 'automation',
    description: 'Broadcast daily KPI digests, ad spend alerts, and lead notifications directly to Slack channels.',
    icon: 'MessageSquare',
    status: 'active',
    latencyMs: 105,
    tags: ['Slack', 'Alerts', 'Daily Digests', 'Team Sync'],
    mcpServer: 'slack-mcp',
  },
  {
    id: 'make_integromat_scenarios',
    name: 'Make.com Visual Workflow Engine',
    category: 'automation',
    description: 'Complex multi-branch marketing scenarios, webhook routers, and JSON payload transforms.',
    icon: 'Repeat',
    status: 'mock',
    latencyMs: 180,
    tags: ['Visual Automation', 'Multi-Branch', 'Routers'],
    mcpServer: 'make-mcp',
  },
  {
    id: 'notion_marketing_wiki',
    name: 'Notion Marketing Hub Database',
    category: 'automation',
    description: 'Sync campaign briefs, brand asset guidelines, creative sprint roadmaps, and content calendars.',
    icon: 'BookOpen',
    status: 'mock',
    latencyMs: 155,
    tags: ['Briefs', 'Content Calendar', 'Brand Guidelines'],
    mcpServer: 'notion-mcp',
  },
  {
    id: 'linear_growth_sprints',
    name: 'Linear Growth Experiments',
    category: 'automation',
    description: 'Log experiment hypotheses, conversion test tickets, and sprint velocity for growth teams.',
    icon: 'CheckCircle',
    status: 'mock',
    latencyMs: 120,
    tags: ['Experiment Backlog', 'Sprints', 'Hypotheses'],
    mcpServer: 'linear-mcp',
  },
  {
    id: 'google_drive_export_engine',
    name: 'Google Drive & Docs Cloud Sync',
    category: 'automation',
    description: 'Auto-sync generated deliverables, PDFs, spreadsheets, and strategy docs directly to team Google Drive.',
    icon: 'HardDrive',
    status: 'active',
    latencyMs: 210,
    tags: ['Google Drive', 'Docs', 'Cloud Storage', 'Team Export'],
    mcpServer: 'gdrive-mcp',
  },

  // ============================================================
  // 7. PAID MEDIA & ACQUISITION (extended, 10 more)
  // ============================================================
  {
    id: 'snapchat_ads_manager',
    name: 'Snapchat Ads Manager',
    category: 'paid_media',
    description: 'AR Lens campaigns, Story ads, and advanced audience targeting across the Snapchat app.',
    icon: 'Ghost',
    status: 'mock',
    latencyMs: 200,
    tags: ['Snapchat', 'AR Lenses', 'Gen Z', 'Story Ads'],
    mcpServer: 'snapchat-mcp',
  },
  {
    id: 'twitch_ads_manager',
    name: 'Twitch Ads & Discovery',
    category: 'paid_media',
    description: 'Mid-roll video sponsorship, display placements, Promoted Channels, and gaming audience targeting.',
    icon: 'Gamepad2',
    status: 'mock',
    latencyMs: 205,
    tags: ['Gaming', 'Mid-Roll', 'Live Stream Sponsorship'],
    mcpServer: 'twitch-mcp',
  },
  {
    id: 'criteo_retail_media',
    name: 'Criteo Retail Media DSP',
    category: 'paid_media',
    description: 'Dynamic retargeting, retailer audiences, and closed-loop performance marketing.',
    icon: 'ShoppingCart',
    status: 'mock',
    latencyMs: 215,
    tags: ['Retargeting', 'Retail Media', 'Dynamic Creative'],
    mcpServer: 'criteo-mcp',
  },
  {
    id: 'taboola_content_discovery',
    name: 'Taboola Content Discovery',
    category: 'paid_media',
    description: 'Native feed placements, content recommendation widgets, and mid-funnel engagement.',
    icon: 'Newspaper',
    status: 'mock',
    latencyMs: 210,
    tags: ['Native Ads', 'Content Recommendation', 'Publishers'],
    mcpServer: 'taboola-mcp',
  },
  {
    id: 'outbrain_native_ads',
    name: 'Outbrain Amplify',
    category: 'paid_media',
    description: 'Open-web native discovery, in-article placements, and audience frequency controls.',
    icon: 'BookOpen',
    status: 'mock',
    latencyMs: 205,
    tags: ['Native Advertising', 'Open Web', 'Content Promotion'],
    mcpServer: 'outbrain-mcp',
  },
  {
    id: 'the_trade_desk_dsp',
    name: 'The Trade Desk DSP',
    category: 'paid_media',
    description: 'Programmatic CTV, audio, display, and advanced first-party data activation at scale.',
    icon: 'Monitor',
    status: 'mock',
    latencyMs: 260,
    tags: ['Programmatic', 'CTV', 'Data-Driven Advertising'],
    mcpServer: 'ttd-mcp',
  },
  {
    id: 'apple_search_ads',
    name: 'Apple Search Ads',
    category: 'paid_media',
    description: 'Search tab campaigns, Suggested Ads, and ASA attribution for App Store growth.',
    icon: 'Apple',
    status: 'mock',
    latencyMs: 185,
    tags: ['App Store', 'Search Tab', 'Mobile Growth'],
    mcpServer: 'apple-search-ads-mcp',
  },
  {
    id: 'applovin_mediation',
    name: 'AppLovin Growth & MAX',
    category: 'paid_media',
    description: 'User acquisition (AXON), in-app bidding mediation, and app revenue telemetry.',
    icon: 'Smartphone',
    status: 'mock',
    latencyMs: 225,
    tags: ['Mobile Ads', 'In-App Bidding', 'User Acquisition'],
    mcpServer: 'applovin-mcp',
  },
  {
    id: 'unity_ads_business',
    name: 'Unity Ads & Monetization',
    category: 'paid_media',
    description: 'Interstitial, rewarded video, and playable ad formats for gaming apps.',
    icon: 'Gamepad2',
    status: 'mock',
    latencyMs: 220,
    tags: ['Rewarded Video', 'Playables', 'Gaming'],
    mcpServer: 'unity-ads-mcp',
  },
  {
    id: 'stackadapt_dsp',
    name: 'StackAdapt Multi-Channel DSP',
    category: 'paid_media',
    description: 'Cross-channel DSP with native, display, connected TV, and real-time integrated placement.',
    icon: 'Layers',
    status: 'mock',
    latencyMs: 240,
    tags: ['Native', 'CTV', 'Cross-Channel DSP'],
    mcpServer: 'stackadapt-mcp',
  },

  // ============================================================
  // 8. ANALYTICS & ATTRIBUTION (extended, 10 more)
  // ============================================================
  {
    id: 'looker_studio_reports',
    name: 'Looker Studio Dashboards',
    category: 'analytics',
    description: 'Programmatic report generation, blended data sources, and shareable marketing dashboards.',
    icon: 'LayoutDashboard',
    status: 'mock',
    latencyMs: 145,
    tags: ['Dashboards', 'Data Blending', 'Reporting Automation'],
    mcpServer: 'looker-studio-mcp',
  },
  {
    id: 'power_bi_analytics',
    name: 'Power BI Marketing Analytics',
    category: 'analytics',
    description: 'Enterprise KPI modeling, DAX measures, and executive marketing performance scorecards.',
    icon: 'BarChart3',
    status: 'mock',
    latencyMs: 155,
    tags: ['DAX', 'Enterprise Reporting', 'KPI Models'],
    mcpServer: 'power-bi-mcp',
  },
  {
    id: 'tableau_dashboards',
    name: 'Tableau Visualization API',
    category: 'analytics',
    description: 'Interactive marketing visualizations, LOD metrics, and audience segmentation exploration.',
    icon: 'PieChart',
    status: 'mock',
    latencyMs: 160,
    tags: ['Visualization', 'LOD Expressions', 'Segmentation'],
    mcpServer: 'tableau-mcp',
  },
  {
    id: 'databox_widgets',
    name: 'Databox KPI Widgets',
    category: 'analytics',
    description: 'Real-time KPI widgets pulling GA4, Meta, and HubSpot metrics into one live dashboard.',
    icon: 'Gauge',
    status: 'mock',
    latencyMs: 125,
    tags: ['Real-time KPIs', 'Widgets', 'Metric Consolidation'],
    mcpServer: 'databox-mcp',
  },
  {
    id: 'snowplow_pipeline',
    name: 'Snowplow Behavioral Pipeline',
    category: 'analytics',
    description: 'Own-your-data event collection, custom schemas, and warehouse-native enrichment.',
    icon: 'Snowflake',
    status: 'mock',
    latencyMs: 165,
    tags: ['Data Ownership', 'Custom Schemas', 'Warehouse-Native'],
    mcpServer: 'snowplow-mcp',
  },
  {
    id: 'appsflyer_mmp',
    name: 'AppsFlyer Attribution CRM',
    category: 'analytics',
    description: 'Install attribution, cost aggregation, SKAdNetwork adjust, and retention ROI.',
    icon: 'Share2',
    status: 'mock',
    latencyMs: 170,
    tags: ['MMP', 'SKAN', 'Retention ROI'],
    mcpServer: 'appsflyer-mcp',
  },
  {
    id: 'branch_universal_links',
    name: 'Branch Deep Linking & Analytics',
    category: 'analytics',
    description: 'Universal links, deferred deep linking, and cross-platform journey attribution.',
    icon: 'GitBranch',
    status: 'mock',
    latencyMs: 165,
    tags: ['Deep Linking', 'Journey Attribution', 'Growth Links'],
    mcpServer: 'branch-mcp',
  },
  {
    id: 'kochava_attribution',
    name: 'Kochava Attribution & Fraud',
    category: 'analytics',
    description: 'Fraud-free app attribution, cost analytics, and multi-touch mobile measurement.',
    icon: 'ShieldCheck',
    status: 'mock',
    latencyMs: 175,
    tags: ['Fraud Prevention', 'Multi-Touch', 'Mobile Measurement'],
    mcpServer: 'kochava-mcp',
  },
  {
    id: 'grafana_metric_alerts',
    name: 'Grafana Marketing Metrics',
    category: 'analytics',
    description: 'Unified metric exploration, Prometheus-style alerting, and revenue anomaly boards.',
    icon: 'Activity',
    status: 'mock',
    latencyMs: 110,
    tags: ['Alerting', 'Anomaly Detection', 'Metric Exploration'],
    mcpServer: 'grafana-mcp',
  },
  {
    id: 'metabase_self_service',
    name: 'Metabase Self-Serve BI',
    category: 'analytics',
    description: 'SQL-free question builder, marketing cohort notebooks, and embedded dashboards.',
    icon: 'Database',
    status: 'mock',
    latencyMs: 120,
    tags: ['Self-Serve BI', 'Cohorts', 'Embedded Analytics'],
    mcpServer: 'metabase-mcp',
  },

  // ============================================================
  // 9. SEO & SCRAPING (extended, 10 more)
  // ============================================================
  {
    id: 'serpapi_query_engine',
    name: 'SerpAPI Search Results API',
    category: 'seo_scraping',
    description: 'Live SERP data for Google, Bing, and YouTube with featured snippet and PAA extraction.',
    icon: 'Search',
    status: 'mock',
    latencyMs: 230,
    tags: ['SERP Data', 'Featured Snippets', 'People Also Ask'],
    mcpServer: 'serpapi-mcp',
  },
  {
    id: 'value_serp_rankings',
    name: 'ValueSERP Rank Tracker',
    category: 'seo_scraping',
    description: 'Affordable rank tracking, local pack monitoring, and daily SERP position snapshots.',
    icon: 'TrendingUp',
    status: 'mock',
    latencyMs: 200,
    tags: ['Rank Tracking', 'Local Pack', 'Daily Snapshots'],
    mcpServer: 'value-serp-mcp',
  },
  {
    id: 'pagespeed_insights_api',
    name: 'PageSpeed Insights API',
    category: 'seo_scraping',
    description: 'Core Web Vitals lab & field data, LCP/CLS/INP audits, and fix recommendations.',
    icon: 'Gauge',
    status: 'mock',
    latencyMs: 240,
    tags: ['Core Web Vitals', 'LCP', 'Site Speed'],
    mcpServer: 'pagespeed-mcp',
  },
  {
    id: 'majestic_backlinks',
    name: 'Majestic Backlink Analytics',
    category: 'seo_scraping',
    description: 'Citation flow, trust flow, and link profile history for topical authority mapping.',
    icon: 'Link2',
    status: 'mock',
    latencyMs: 215,
    tags: ['Trust Flow', 'Citation Flow', 'Link History'],
    mcpServer: 'majestic-mcp',
  },
  {
    id: 'ubersuggest_kw_tool',
    name: 'Ubersuggest Keyword Tool',
    category: 'seo_scraping',
    description: 'Keyword difficulty, content ideas, and competitor site-wide strategy extraction.',
    icon: 'Lightbulb',
    status: 'mock',
    latencyMs: 190,
    tags: ['Keyword Difficulty', 'Content Ideas', 'Competitor Strategy'],
    mcpServer: 'ubersuggest-mcp',
  },
  {
    id: 'seobility_site_audit',
    name: 'Seobility SEO Analyzer',
    category: 'seo_scraping',
    description: 'Automated 80+ point site audits, issue grouping by priority, and SERP share checks.',
    icon: 'ClipboardCheck',
    status: 'mock',
    latencyMs: 210,
    tags: ['Site Audits', 'Priority Grouping', 'SERP Share'],
    mcpServer: 'seobility-mcp',
  },
  {
    id: 'webpagetest_lab',
    name: 'WebPageTest Lab Runs',
    category: 'seo_scraping',
    description: 'Multi-location performance waterfalls, filmstrip capture, and mobile throttling tests.',
    icon: 'Timer',
    status: 'mock',
    latencyMs: 260,
    tags: ['Waterfalls', 'Multi-Location', 'Filmstrip'],
    mcpServer: 'webpagetest-mcp',
  },
  {
    id: 'google_keyword_planner',
    name: 'Google Keyword Planner',
    category: 'seo_scraping',
    description: 'Search volume forecasts, bid simulations, and seasonal keyword trends from Ads data.',
    icon: 'KeySquare',
    status: 'mock',
    latencyMs: 185,
    tags: ['Search Volume', 'Bid Forecasts', 'Seasonality'],
    mcpServer: 'keyword-planner-mcp',
  },
  {
    id: 'lighthouse_auditor',
    name: 'Lighthouse Programmatic Audit',
    category: 'seo_scraping',
    description: 'Automated PWA, performance, accessibility, and SEO scoring across page templates.',
    icon: 'Beacon',
    status: 'mock',
    latencyMs: 245,
    tags: ['Audit Scoring', 'Accessibility', 'Performance Budgets'],
    mcpServer: 'lighthouse-mcp',
  },
  {
    id: 'schema_validator',
    name: 'Schema.org Structured Data',
    category: 'seo_scraping',
    description: 'Rich-result testing, JSON-LD validation, and FAQ/Product structured data coverage.',
    icon: 'Braces',
    status: 'mock',
    latencyMs: 175,
    tags: ['JSON-LD', 'Rich Results', 'Structured Data'],
    mcpServer: 'schema-mcp',
  },

  // ============================================================
  // 10. CRM & RETENTION LIFECYCLE (extended, 10 more)
  // ============================================================
  {
    id: 'drip_lifecycle_email',
    name: 'Drip Lifecycle Marketing',
    category: 'crm_retention',
    description: 'Multi-channel lifecycle journeys, revenue attribution, and personalization tokens.',
    icon: 'Droplet',
    status: 'mock',
    latencyMs: 150,
    tags: ['Lifecycle', 'Revenue Attribution', 'Personalization'],
    mcpServer: 'drip-mcp',
  },
  {
    id: 'iterable_cross_channel',
    name: 'Iterable Cross-Channel',
    category: 'crm_retention',
    description: 'Cross-channel campaigns with catalogs, experiments, and real-time personalization.',
    icon: 'Repeat',
    status: 'mock',
    latencyMs: 155,
    tags: ['Cadences', 'Experiments', 'Product Catalogs'],
    mcpServer: 'iterable-mcp',
  },
  {
    id: 'sendgrid_email_engine',
    name: 'SendGrid Transactional Email',
    category: 'crm_retention',
    description: 'Transactional delivery, delivery analytics, and suppression list management.',
    icon: 'Send',
    status: 'mock',
    latencyMs: 115,
    tags: ['Transactional', 'Delivery Analytics', 'Suppression'],
    mcpServer: 'sendgrid-mcp',
  },
  {
    id: 'postmark_delivery',
    name: 'Postmark Fast Delivery',
    category: 'crm_retention',
    description: 'Low-latency transactional email, ping/bounce webhooks, and message stream APIs.',
    icon: 'MailCheck',
    status: 'mock',
    latencyMs: 95,
    tags: ['Transactional Email', 'Webhooks', 'Low Latency'],
    mcpServer: 'postmark-mcp',
  },
  {
    id: 'onesignal_push',
    name: 'OneSignal Push & In-App',
    category: 'crm_retention',
    description: 'Cross-platform push, in-app messaging, and player segmentation with automated triggers.',
    icon: 'Bell',
    status: 'mock',
    latencyMs: 120,
    tags: ['Push Notifications', 'In-App Messaging', 'Segments'],
    mcpServer: 'onesignal-mcp',
  },
  {
    id: 'close_crm_sales',
    name: 'Close.com Built-in Dialer',
    category: 'crm_retention',
    description: 'Voice & SMS sales workflow automation, call coaching, and pipeline cadence tracking.',
    icon: 'PhoneCall',
    status: 'mock',
    latencyMs: 135,
    tags: ['Dialer', 'Call Coaching', 'SMS Sales'],
    mcpServer: 'close-mcp',
  },
  {
    id: 'zendesk_sell',
    name: 'Zendesk Sell CRM',
    category: 'crm_retention',
    description: 'Lead routing, quotes & proposals, and sales productivity automation for B2B teams.',
    icon: 'Headphones',
    status: 'mock',
    latencyMs: 140,
    tags: ['Lead Routing', 'Quotes', 'B2B Sales'],
    mcpServer: 'zendesk-sell-mcp',
  },
  {
    id: 'freshsales_crm',
    name: 'Freshsales Freddy AI',
    category: 'crm_retention',
    description: 'AI-powered lead scoring, journey orchestration, and contact lifecycle management.',
    icon: 'Sprout',
    status: 'mock',
    latencyMs: 130,
    tags: ['Lead Scoring', 'Journeys', 'Contact Lifecycle'],
    mcpServer: 'freshsales-mcp',
  },
  {
    id: 'campaign_monitor',
    name: 'Campaign Monitor Email',
    category: 'crm_retention',
    description: 'Drag-and-drop newsletters, automated journeys, and transactional sends for agencies.',
    icon: 'Palette',
    status: 'mock',
    latencyMs: 135,
    tags: ['Newsletters', 'Agency Tools', 'Automations'],
    mcpServer: 'campaign-monitor-mcp',
  },
  {
    id: 'constant_contact_events',
    name: 'Constant Contact Events & Email',
    category: 'crm_retention',
    description: 'Email marketing plus event registration, ticketing, and attendee follow-up flows.',
    icon: 'Calendar',
    status: 'mock',
    latencyMs: 140,
    tags: ['Events', 'Ticketing', 'Attendee Follow-up'],
    mcpServer: 'constant-contact-mcp',
  },

  // ============================================================
  // 11. CRO, CMS & CREATIVE (extended, 10 more)
  // ============================================================
  {
    id: 'hotjar_experience_insights',
    name: 'Hotjar Heatmaps & Recording',
    category: 'cro_creative',
    description: 'Behavioral heatmaps, session recordings, and 1-2-1 conversation pause studies.',
    icon: 'Thermometer',
    status: 'mock',
    latencyMs: 145,
    tags: ['Heatmaps', 'Session Recordings', 'Feedback'],
    mcpServer: 'hotjar-mcp',
  },
  {
    id: 'microsoft_clarity',
    name: 'Microsoft Clarity Free Analytics',
    category: 'cro_creative',
    description: 'Free session replays, heatmaps, dead-click tracking, and rage-click discovery.',
    icon: 'MousePointerClick',
    status: 'mock',
    latencyMs: 110,
    tags: ['Session Replays', 'Dead Clicks', 'Rage Clicks'],
    mcpServer: 'clarity-mcp',
  },
  {
    id: 'google_tag_manager',
    name: 'Google Tag Manager',
    category: 'cro_creative',
    description: 'Container-based tag deployment, data-layer event wiring, and preview debug mode.',
    icon: 'Box',
    status: 'mock',
    latencyMs: 105,
    tags: ['Data Layer', 'Tag Deployment', 'Debug Mode'],
    mcpServer: 'gtm-mcp',
  },
  {
    id: 'usertesting_research',
    name: 'UserTesting Research',
    category: 'cro_creative',
    description: 'On-demand video usability tests, first-click tests, and moderated research sessions.',
    icon: 'Video',
    status: 'mock',
    latencyMs: 230,
    tags: ['Usability Tests', 'First Click', 'Moderated Research'],
    mcpServer: 'usertesting-mcp',
  },
  {
    id: 'qualaroo_takeaway',
    name: 'Qualaroo Nudge Surveys',
    category: 'cro_creative',
    description: 'Context-aware micro-surveys with skip logic, translations, and sentiment tags.',
    icon: 'MessagesSquare',
    status: 'mock',
    latencyMs: 150,
    tags: ['Micro Surveys', 'Skip Logic', 'Sentiment'],
    mcpServer: 'qualaroo-mcp',
  },
  {
    id: 'crazyegg_metrics',
    name: 'Crazy Egg Snapshots',
    category: 'cro_creative',
    description: 'A/B heatmap testing, confetti reports, scroll maps, and overlay analytics.',
    icon: 'Egg',
    status: 'mock',
    latencyMs: 145,
    tags: ['Confetti Reports', 'Scroll Maps', 'Overlays'],
    mcpServer: 'crazyegg-mcp',
  },
  {
    id: 'figma_design_api',
    name: 'Figma Design Tokens & Assets',
    category: 'cro_creative',
    description: 'Extract brand tokens, export playbooks, and sync marketing assets from Figma files.',
    icon: 'PenTool',
    status: 'mock',
    latencyMs: 190,
    tags: ['Design Tokens', 'Brand Assets', 'Playbooks'],
    mcpServer: 'figma-mcp',
  },
  {
    id: 'adobe_express_creatives',
    name: 'Adobe Express Templates',
    category: 'cro_creative',
    description: 'Auto-generate on-brand social posts, video reels, and PDF one-pagers in bulk.',
    icon: 'Image',
    status: 'mock',
    latencyMs: 245,
    tags: ['Bulk Creatives', 'Social Posts', 'Video Reels'],
    mcpServer: 'adobe-express-mcp',
  },
  {
    id: 'instapage_landing',
    name: 'Instapage Post-Click Landing',
    category: 'cro_creative',
    description: 'Post-click personalization, Instablocks, and AMP-accelerated landing variants.',
    icon: 'Rocket',
    status: 'mock',
    latencyMs: 160,
    tags: ['Post-Click Optimization', 'Instablocks', 'AMP'],
    mcpServer: 'instapage-mcp',
  },
  {
    id: 'quantcast_measure',
    name: 'Quantcast Measure Audiences',
    category: 'cro_creative',
    description: 'Privacy-first audience insights and reach measurement across programmatic inventory.',
    icon: 'Users',
    status: 'mock',
    latencyMs: 175,
    tags: ['Audience Insights', 'Reach Measurement', 'Privacy-First'],
    mcpServer: 'quantcast-mcp',
  },

  // ============================================================
  // 12. AUTOMATION & WORKSPACE OPS (extended, 10 more)
  // ============================================================
  {
    id: 'airtable_ops_base',
    name: 'Airtable Marketing Ops',
    category: 'automation',
    description: 'Campaign trackers, content calendars, and creative review bases with automations.',
    icon: 'Table',
    status: 'mock',
    latencyMs: 130,
    tags: ['Campaign Tracker', 'Content Calendar', 'Automations'],
    mcpServer: 'airtable-mcp',
  },
  {
    id: 'google_sheets_pipeline',
    name: 'Google Sheets Live Reports',
    category: 'automation',
    description: 'Push blended KPI tables, spend reconciliations, and statuses into shared sheets.',
    icon: 'Table2',
    status: 'mock',
    latencyMs: 105,
    tags: ['Live KPI Tables', 'Spend Reconciliation', 'Team Sync'],
    mcpServer: 'gsheets-mcp',
  },
  {
    id: 'asana_goals_projects',
    name: 'Asana Growth Projects',
    category: 'automation',
    description: 'Quarterly growth goals, campaign milestones, and approval workflows in Asana.',
    icon: 'Target',
    status: 'mock',
    latencyMs: 120,
    tags: ['Growth Goals', 'Milestones', 'Approval Workflows'],
    mcpServer: 'asana-mcp',
  },
  {
    id: 'trello_content_board',
    name: 'Trello Content Boards',
    category: 'automation',
    description: 'Kanban content pipelines, deadline power-ups, and recruitment-style creative review lanes.',
    icon: 'SquareKanban',
    status: 'mock',
    latencyMs: 110,
    tags: ['Kanban', 'Content Pipelines', 'Power-Ups'],
    mcpServer: 'trello-mcp',
  },
  {
    id: 'n8n_workflow_engine',
    name: 'n8n Self-Hosted Workflows',
    category: 'automation',
    description: 'Open-source workflow automation with LLM nodes, error queues, and webhook triggers.',
    icon: 'Workflow',
    status: 'mock',
    latencyMs: 140,
    tags: ['Self-Hosted', 'LLM Nodes', 'Webhooks'],
    mcpServer: 'n8n-mcp',
  },
  {
    id: 'retool_internal_dashboards',
    name: 'Retool Internal Dashboards',
    category: 'automation',
    description: 'Internal marketing ops tools, approval UIs, and admin panels on customer data.',
    icon: 'LayoutGrid',
    status: 'mock',
    latencyMs: 150,
    tags: ['Internal Tools', 'Admin Panels', 'Approval UIs'],
    mcpServer: 'retool-mcp',
  },
  {
    id: 'telegram_alert_bot',
    name: 'Telegram Marketing Bot',
    category: 'automation',
    description: 'Push KPI digests, anomaly alerts, and campaign notifications straight to Telegram groups.',
    icon: 'Send',
    status: 'mock',
    latencyMs: 95,
    tags: ['Bot Alerts', 'KPI Digests', 'Group Notifications'],
    mcpServer: 'telegram-mcp',
  },
  {
    id: 'whatsapp_business_api',
    name: 'WhatsApp Business Messaging',
    category: 'automation',
    description: 'Transactional updates, opt-in flows, and conversational commerce campaigns via Cloud API.',
    icon: 'MessageCircle',
    status: 'mock',
    latencyMs: 115,
    tags: ['Transactional Messaging', 'Opt-In Flows', 'Conversational Commerce'],
    mcpServer: 'whatsapp-mcp',
  },
  {
    id: 'cloudconvert_deliverables',
    name: 'CloudConvert File Pipeline',
    category: 'automation',
    description: 'Ad-hoc PDF, DOCX, PPTX, and XLSX conversions in automated rack deliverable flows.',
    icon: 'FileOutput',
    status: 'mock',
    latencyMs: 135,
    tags: ['File Conversion', 'Deliverables', 'Format Wrangling'],
    mcpServer: 'cloudconvert-mcp',
  },
  {
    id: 'cron_jobs_scheduler',
    name: 'Cron Scheduled Automations',
    category: 'automation',
    description: 'Time-based triggers for nightly syncs, digest sending, and recurring report generation.',
    icon: 'Clock',
    status: 'mock',
    latencyMs: 100,
    tags: ['Schedules', 'Nightly Syncs', 'Recurring Reports'],
    mcpServer: 'cron-mcp',
  },
];
