// ============================================================
// Infinall Chat - Native DOCX Document Generator
// ============================================================

import {
  Document,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  HeadingLevel,
  AlignmentType,
  WidthType,
  Packer,
} from 'docx';

export interface DocxOptions {
  title: string;
  subtitle?: string;
  companyName?: string;
  author?: string;
  content?: string;
  sections?: Array<{
    heading?: string;
    paragraphs?: string[];
    callout?: string;
    table?: {
      headers: string[];
      rows: string[][];
    };
  }>;
}

export class DocxBuilder {
  static async buildDocument(options: DocxOptions | string): Promise<Buffer> {
    let parsed: DocxOptions;

    if (typeof options === 'string') {
      try {
        parsed = JSON.parse(options);
      } catch {
        parsed = this.parseMarkdownToSections(options);
      }
    } else {
      parsed = options;
      if (parsed.content && (!parsed.sections || parsed.sections.length === 0)) {
        const fromMd = this.parseMarkdownToSections(parsed.content);
        parsed.title = parsed.title || fromMd.title;
        parsed.sections = fromMd.sections;
      }
    }

    const docChildren: (Paragraph | Table)[] = [];

    // Title & Header
    docChildren.push(
      new Paragraph({
        text: parsed.title || 'Infinall Strategic Brief',
        heading: HeadingLevel.TITLE,
        spacing: { after: 150 },
      })
    );

    if (parsed.subtitle) {
      docChildren.push(
        new Paragraph({
          children: [
            new TextRun({
              text: parsed.subtitle,
              italics: true,
              color: '64748b',
              size: 24,
            }),
          ],
          spacing: { after: 300 },
        })
      );
    }

    docChildren.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `Generated by Infinall Chat | Autonomous Marketing Intelligence`,
            size: 18,
            color: '94a3b8',
            italics: true,
          }),
        ],
        spacing: { after: 350 },
      })
    );

    // Sections
    const sections = parsed.sections || [];
    for (const section of sections) {
      if (section.heading) {
        docChildren.push(
          new Paragraph({
            text: section.heading,
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 300, after: 150 },
          })
        );
      }

      if (section.callout) {
        docChildren.push(
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({
                    children: [
                      new Paragraph({
                        children: [
                          new TextRun({
                            text: section.callout,
                            italics: true,
                            color: '0891b2',
                            size: 20,
                          }),
                        ],
                      }),
                    ],
                    shading: { fill: 'f0fdfa' },
                    margins: { top: 120, bottom: 120, left: 150, right: 150 },
                  }),
                ],
              }),
            ],
          })
        );
        docChildren.push(new Paragraph({ spacing: { after: 150 } }));
      }

      if (section.paragraphs && section.paragraphs.length > 0) {
        for (const p of section.paragraphs) {
          const isBullet = p.startsWith('• ') || p.startsWith('- ') || p.startsWith('* ');
          const cleanP = p.replace(/^[•\-*]\s+/, '');
          
          docChildren.push(
            new Paragraph({
              bullet: isBullet ? { level: 0 } : undefined,
              children: [
                new TextRun({
                  text: cleanP.replace(/\*\*/g, ''),
                  bold: p.includes('**') && !isBullet,
                  size: 22,
                  color: '1e293b',
                }),
              ],
              spacing: { after: 120 },
            })
          );
        }
      }

      if (section.table && section.table.headers.length > 0) {
        const headerRow = new TableRow({
          tableHeader: true,
          children: section.table.headers.map(
            (h) =>
              new TableCell({
                children: [
                  new Paragraph({
                    children: [new TextRun({ text: h.replace(/\*\*/g, ''), bold: true, color: 'ffffff', size: 20 })],
                    alignment: AlignmentType.CENTER,
                  }),
                ],
                shading: { fill: '0f172a' },
                margins: { top: 100, bottom: 100, left: 100, right: 100 },
              })
          ),
        });

        const dataRows = section.table.rows.map(
          (row, rIdx) =>
            new TableRow({
              children: row.map(
                (cell) =>
                  new TableCell({
                    children: [
                      new Paragraph({
                        children: [new TextRun({ text: cell.replace(/\*\*/g, ''), size: 20 })],
                      }),
                    ],
                    shading: { fill: rIdx % 2 === 0 ? 'f8fafc' : 'ffffff' },
                    margins: { top: 80, bottom: 80, left: 80, right: 80 },
                  })
              ),
            })
        );

        docChildren.push(
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [headerRow, ...dataRows],
          })
        );
        docChildren.push(new Paragraph({ spacing: { after: 200 } }));
      }
    }

    const doc = new Document({
      sections: [
        {
          properties: {},
          children: docChildren,
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);
    return buffer;
  }

  private static parseMarkdownToSections(md: string): DocxOptions {
    const lines = md.split('\n');
    let title = 'Infinall Strategic Deliverable';
    const sections: DocxOptions['sections'] = [];
    let currentSection: {
      heading?: string;
      paragraphs: string[];
      callout?: string;
      table?: { headers: string[]; rows: string[][] };
    } = {
      paragraphs: [],
    };

    let inTable = false;
    let tableHeaders: string[] = [];
    let tableRows: string[][] = [];

    const flushTable = () => {
      if (inTable && tableHeaders.length > 0) {
        currentSection.table = {
          headers: tableHeaders,
          rows: tableRows,
        };
        inTable = false;
        tableHeaders = [];
        tableRows = [];
      }
    };

    for (const line of lines) {
      const trimmed = line.trim();

      if (trimmed.startsWith('|') && trimmed.endsWith('|')) {
        if (trimmed.includes('---')) {
          continue;
        }
        const cells = trimmed.split('|').map((c) => c.trim()).filter(Boolean);
        if (!inTable) {
          inTable = true;
          tableHeaders = cells;
          tableRows = [];
        } else {
          tableRows.push(cells);
        }
        continue;
      } else if (inTable) {
        flushTable();
      }

      if (trimmed.startsWith('# ')) {
        title = trimmed.replace(/^#\s+/, '').replace(/\*\*/g, '');
      } else if (trimmed.startsWith('## ') || trimmed.startsWith('### ')) {
        flushTable();
        if (currentSection.paragraphs.length > 0 || currentSection.heading || currentSection.table) {
          sections.push(currentSection);
        }
        currentSection = {
          heading: trimmed.replace(/^#+\s+/, '').replace(/\*\*/g, ''),
          paragraphs: [],
        };
      } else if (trimmed.startsWith('> ')) {
        currentSection.callout = trimmed.replace(/^>\s+/, '').replace(/\*\*/g, '');
      } else if (trimmed) {
        currentSection.paragraphs.push(trimmed);
      }
    }

    flushTable();
    if (currentSection.paragraphs.length > 0 || currentSection.heading || currentSection.table) {
      sections.push(currentSection);
    }

    return { title, sections };
  }
}
